[project]
name = "quanxai-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.2.0",
    "langgraph>=1.0.5",
    "pandas>=2.3.3",
]
